fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
    private_lane :certificates do
        match(app_identifier: 'com.dsv.guitarproficiency', type: 'development', readonly: true)
        match(app_identifier: 'com.dsv.guitarproficiency', type: 'appstore', readonly: true)
    end
    private_lane :build do
        certificates
        increment_build_number(xcodeproj: './ios/GUITAR_PROFICIENCY.xcodeproj')
        gym(scheme: 'GUITAR_PROFICIENCY', project: './ios/GUITAR_PROFICIENCY.xcodeproj')
    end
    lane :beta do
        build
        pilot
        commit_version_bump(message: 'Bump build', xcodeproj: './ios/GUITAR_PROFICIENCY.xcodeproj')
        push_to_git_remote
    end
end

platform :android do
  # Android Lanes
end